### ISSUE TITLE
refactor 

### ISSUE THREAD

**Issue by rowanibrahem** [Dina266/mini_chat_app#3]
ممكن تمسحي الview model من الsplash لاننا مش هنحتاجه و تقسمي الكود لwidgets  اقل و تحطيه جوه فايل widgets

**Comment by rowanibrahem** [comment]
ممكن تزودي كلمة واتس اب عد الايقونة و تقللي المسافة بينها و لن اخر ايقون شوية 
@Dina266

**Comment by Dina266** [comment]
Refactor Done
